#Makefile for Joshua Osborne's Dining Philosopher's Problem for Assignment 3
#CSC 345 
#9 May 2017

diningPhilosophers: DiningPhilosophers.c
	gcc -o diningPhilosophers -pthread DiningPhilosophers.c

clean:
	rm diningPhilosophers
